import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.*;
import java.net.InetAddress;

/**
 * Created by dianyo on 2016/12/12.
 */
public class App {
    private JLabel accountLabel;
    private JTextField accountText;
    private JPasswordField passText;
    private JButton uploadButton;
    private JPanel articlePanel;
    private JTextField boardText;
    private JTextArea contentText;
    private JLabel passLabel;
    private JLabel boardLabel;
    private JLabel titleLabel;
    private JTextField titleText;
    private JLabel contentLabel;
    private JPanel mainPanel;
    public JFrame frame;
    private Object lock = new Object();

    public App() {
        this.setButton();
        frame = new JFrame("App");
        frame.setContentPane(mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    private void setButton() {

        uploadButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int n = JOptionPane.showOptionDialog(frame,
                        "Are you sure to upload the article?",
                        "Upload",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        new Object[]{"Yes", "No"},
                        "Yes");
                if (n == JOptionPane.YES_OPTION) try {
                    Writer writer = new BufferedWriter(new OutputStreamWriter(
                            new FileOutputStream("P_input.txt")));
                    writer.write("<ID>" + accountText.getText() + "</ID>\n");
                    writer.write("<PASS>" + String.valueOf(passText.getPassword()) + "</PASS>\n");
                    writer.write("<BOARD>" + boardText.getText() + "</BOARD>\n");
                    writer.write("<P>" + titleText.getText() + "</P>\n");
                    writer.write("<CONTENT>" + contentText.getText() + "</CONTENT>\n");
                    writer.write("<EXIT>");
                    writer.flush();

                    frame.dispose();
                    frame.setVisible(false);
                    String fileName = "P_input.txt";
                    Instruction instruction = new Instruction(fileName);
                    try {
                        InetAddress address = InetAddress.getByName("ptt.cc");
                        String ip = address.getHostAddress();
                        System.out.println("ip = " +  ip);
                        ClientSocket socket = new ClientSocket(ip, 23, instruction, 0);
                    } catch (Exception e1) {
                        System.out.println(e1.getMessage());
                        System.exit(0);
                    }
                } catch (Exception e1) {
                    System.out.println(e1.getMessage());
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        accountLabel = new JLabel();
        accountLabel.setFont(new Font("Fira Code Retina", accountLabel.getFont().getStyle(), 16));
        accountLabel.setText("Account:");
        mainPanel.add(accountLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(140, 20), null, 0, false));
        accountText = new JTextField();
        mainPanel.add(accountText, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(203, 26), null, 0, false));
        passLabel = new JLabel();
        passLabel.setFont(new Font("Fira Code Retina", passLabel.getFont().getStyle(), 16));
        passLabel.setText("Password:");
        mainPanel.add(passLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(140, 20), null, 0, false));
        passText = new JPasswordField();
        mainPanel.add(passText, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        articlePanel = new JPanel();
        articlePanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(articlePanel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        articlePanel.setBorder(BorderFactory.createTitledBorder("Article"));
        boardLabel = new JLabel();
        boardLabel.setFont(new Font("Fira Code Retina", boardLabel.getFont().getStyle(), 16));
        boardLabel.setText("Board:");
        articlePanel.add(boardLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(192, 20), null, 0, false));
        boardText = new JTextField();
        articlePanel.add(boardText, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        titleLabel = new JLabel();
        titleLabel.setFont(new Font("Fira Code Retina", titleLabel.getFont().getStyle(), 16));
        titleLabel.setText("Title:");
        articlePanel.add(titleLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(192, 20), null, 0, false));
        titleText = new JTextField();
        articlePanel.add(titleText, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        contentLabel = new JLabel();
        contentLabel.setFont(new Font("Fira Code Retina", contentLabel.getFont().getStyle(), 16));
        contentLabel.setText("Content:");
        articlePanel.add(contentLabel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(192, 20), null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        articlePanel.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(30, 100), null, 0, false));
        contentText = new JTextArea();
        scrollPane1.setViewportView(contentText);
        uploadButton = new JButton();
        uploadButton.setText("Upload");
        mainPanel.add(uploadButton, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        accountLabel.setLabelFor(accountText);
        contentLabel.setLabelFor(scrollPane1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
